name: ci

on: [push]
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: npm i -g yarn lerna
      - run: lerna bootstrap
      - run: yarn lint
      - run: yarn typecheck
      - run: lerna run test
