name: ci

5
on:
  pull_request:
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - 'yarn.lock'
      - '.eslintrc'
      - '.eslintignore'
      - '.prettierrc'
      - '.prettierignore'
      - '.github/workflows/ci.yml'
  push:
    branches:
      - dev
      - prod

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm i -g yarn lerna
      - run: lerna bootstrap
      - run: yarn format:check
      - run: yarn lint
      - run: yarn build
      - run: npm run test
