name: ci

on:
  pull_request:
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '.eslintrc'
      - '.eslintignore'
      - '.prettierignore'
      - '.github/workflows/ci.yml'
  push:
    branches:
      - main

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
      - run: npm run build
      - run: npm run test
